# Generated by Django 4.2.6 on 2023-10-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(default='', max_length=255, verbose_name='Короткое описание'),
        ),
    ]
